name: Build a firmware on demand

on:
  workflow_dispatch:
    inputs:
      keyboard:
        description: "Keyboard"
        required: true
        type: choice
        default: "keyball39"
        options:
          - keyball39
      keymap:
        description: "Keymap"
        required: true
        type: string
        default: "fumi"

jobs:
  build:
    uses: ./.github/workflows/build-firmware.yml
    with:
      qmk_version: "0.22.14"
      keyboard: ${{ inputs.keyboard }}
      keymap: ${{ inputs.keymap }}
