name: Build fumi firmware

on:
  push:
    paths:
      - "qmk_firmware/keyboards/keyball/**.mk"
      - "qmk_firmware/keyboards/keyball/**.c"
      - "qmk_firmware/keyboards/keyball/**.h"
      - "qmk_firmware/keyboards/keyball/**.json"
      - ".github/**.yml"
    tags-ignore:
      - "*"
    branches:
      - "*"

  pull_request:
    paths:
      - "qmk_firmware/keyboards/keyball/**.mk"
      - "qmk_firmware/keyboards/keyball/**.c"
      - "qmk_firmware/keyboards/keyball/**.h"
      - "qmk_firmware/keyboards/keyball/**.json"
      - ".github/**.yml"

  workflow_call: {}

jobs:
  build:
    # matrixを削除し、直接 keyball39 と fumi を指定
    uses: ./.github/workflows/build-firmware.yml
    with:
      qmk_version: "0.22.14"
      keyboard: keyball39
      keymap: fumi

  check-size:
    name: Check size
    runs-on: ubuntu-22.04
    needs:
      - build

    steps:
      - uses: actions/download-artifact@v6
        with:
          pattern: "*-firmware"
          merge-multiple: true

      - name: List size of firmwares
        run: |
          # hexファイルが存在する場合のみ実行
          for f in *.hex ; do
            if [ -f "$f" ]; then
              cut -c 2,3 $f | awk '{s+=strtonum("0x" $1)}END{printf "%5d/28672 (%2d%%, %5d bytes free) ",s,s*100/28672,28672-s}'
              echo $f
            fi
          done
