name: Release firmwares

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    name: Build firmwares
    # 他の修正で build-all.yml が keyball39:fumi のみに絞られている前提
    uses: ./.github/workflows/build-all.yml

  deploy:
    name: Deploy firmwares
    runs-on: ubuntu-22.04
    needs:
      - build

    steps:
      - name: Checkout source
        uses: actions/checkout@v4 # v6はまだ存在しないため最新安定版のv4を推奨

      - name: Archive Keyball39 firmwares
        uses: ./.github/actions/release-archive
        with: { name: keyball39 }

      # 他の機種（44, 61, 46, one47）の Archive ステップは削除

      - name: List archives
        run: ls -l *.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: ${{ contains(github.ref_name, '-alpha.') || contains(github.ref_name, '-beta.') }}
          files: |
            *.zip
          fail_on_unmatched_files: true
          generate_release_notes: true
          append_body: true
